const ADD_FIN4_TOKEN = 'ADD_FIN4_TOKEN';
const ADD_MULTIPLE_FIN4_TOKENS = 'ADD_MULTIPLE_FIN4_TOKENS';
const ADD_CLAIM = 'ADD_CLAIM';
const ADD_MULTIPLE_CLAIMS = 'ADD_MULTIPLE_CLAIMS';
const APPROVE_CLAIM = 'APPROVE_CLAIM';
const ADD_ADDRESS = 'ADD_ADDRESS';
const UPDATE_BALANCE = 'UPDATE_BALANCE';
const UPDATE_MULTIPLE_BALANCES = 'UPDATE_MULTIPLE_BALANCES';
const ADD_MULTIPLE_PROOF_TYPES = 'ADD_MULTIPLE_PROOF_TYPES';
const SET_DEFAULT_ACCOUNT = 'SET_DEFAULT_ACCOUNT';

export {
	ADD_FIN4_TOKEN,
	ADD_MULTIPLE_FIN4_TOKENS,
	ADD_CLAIM,
	ADD_MULTIPLE_CLAIMS,
	APPROVE_CLAIM,
	ADD_ADDRESS,
	UPDATE_BALANCE,
	UPDATE_MULTIPLE_BALANCES,
	ADD_MULTIPLE_PROOF_TYPES,
	SET_DEFAULT_ACCOUNT
};
