const ADD_FIN4_TOKEN = 'ADD_FIN4_TOKEN';
const ADD_MULTIPLE_FIN4_TOKENS = 'ADD_MULTIPLE_FIN4_TOKENS';
const ADD_CLAIM = 'ADD_CLAIM';
const ADD_MULTIPLE_CLAIMS = 'ADD_MULTIPLE_CLAIMS';

export { ADD_FIN4_TOKEN, ADD_MULTIPLE_FIN4_TOKENS, ADD_CLAIM, ADD_MULTIPLE_CLAIMS };
